version: "3.3"

services:
  apt-decor-api:
    container_name: apt-decor
    restart: always
    image: node:20.10.0
    ports:
      - "4001:3024"
    volumes:
      - ./:/usr/src/apt-decor
    working_dir: /usr/src/apt-decor

    networks:
      - monorepo_network

      # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  apt-decor-batch:
    container_name: apt-decor-batch
    restart: always
    image: node:20.10.0
    ports:
      - "4002:3025"
    volumes:
      - ./:/usr/src/apt-decor-batch
    working_dir: /usr/src/apt-decor-batch

    networks:
      - monorepo_network

      # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

networks:
  monorepo_network:
    driver: bridge
# apt-decor-next: localhost:4000 <=> container:3000
# apt-decor-api: localhost:4000 <=> container:3007
# apt-decor-batch: localhost:4000 <=> container:3008
